# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package manifest and lockfiles
COPY package.json package-lock.json* pnpm-lock.yaml* ./

# Install global dependency for shx and project dependencies
RUN npm install -g shx && npm install --ignore-scripts

# Copy the rest of the project
COPY . .

# Build the project
RUN npm run build

# Set the startup command
CMD ["npm", "start"]
